# Site settings
title: Bumjun Park
email: bpark67@uw.edu
description: "Personal webiste for Bumjun Park, Ph.D. Student, Department of Biostatistics, University of Washington"


# Team names, titles and social links
people:
- name:
- name: Bumjun Park
  pic: 5
  position: Ph.D. Student
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/bumjun-park-4b8398241/
    - title: github
      url: http://github.com/bpark67
    - title: stack-overflow
      url: https://stackoverflow.com/users/19822406/themoonandsixpence

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bumjun-park-4b8398241/
  - title: github
    url: http://github.com/bpark67
  - title: stack-overflow
    url: https://stackoverflow.com/users/19822406/themoonandsixpence
  - title: orcid
    url: https://orcid.org/0009-0008-0361-3810



# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag